"""
quotes of the 9 tf2 characters.

"""

CLASSES = {
    'red_spy' : [
            "Gentlemen.",
            "I never really was on your side.",
            "They should call you whiners Dr. NOOOOOOOOOOOOOOOOOOOOO!",
            "Promise not to bleed on my suit, and I'll kill you quickly.",
            "Our influence grows!",
            "I murdered your toys as well!",
            "I appear to have burst into flames!",
            "I do believe I'm on fire.",
            "It seems I am not the only spy.",
            "Here lies scout. He ran fast, and died a virgin.",
            "After you.",
            "Shall we?",
            "Peekaboo!",
            "I'll be seeing you!",
            "This will be the last time you see me.",
            "Just lay your weapons down and walk away.",
            "You got blood on my suit!",
            "Oh dear, I've made quite a mess.",
            "The outcome was never really in doubt.",
            "You are all incompetent cowards!",
            "Well, this was a disappointment.",
            "You know, hiding won't save you.",
            "Sorry to pop in unannounced.",
            "Why don't we just give up, pardner?",
            "Everyone back to base, pardner.",
            "May I make a suggestion? Run.",
            "Thank you, laborer!",
            "y I borrow your earpiece? This is Scout! Rainbows make me cry! Over!",
            "Well, off to visit your mother!",
            "Here lies Scout. He ran fast, and died a virgin!",
            "At least you died for honor, and my amusement.",
            "Don't feel bad, you did a fine job throwing your little balls around!",
            "Kaboom indeed, you drunken wretch!",
            "The black Scottish cyclops, now extinct!",
            "I merely finished what your liver started!",
            "You die as you lived, morbidly obese.",
            "You disgust me, filthy jar-man!",
            "I have been shown who is the boss!",
            "Jarate?!",
            "I HATE you.",
            "Is this...? MON DIEU!",
            "I'm coming for you!",
            "I think not.",
            "But of course.",
            "Top shelf!",
            "What a disaster!",
            "Does it hurt when I do that? It does, doesn't it?!",
            "With my apologies!",
        ],
    'red_soldier' : [
            "Maggots!",
            "Give 'em hell, boys!",
            "The worm has turned, gentlemen!",
            "I am going to strangle you with your own frilly training bra!",
            "This is my world, you are not welcome in my world!",
            "If God had wanted you to live he would not have created ME!",
            "Every one of you deserves a medal!",
            "Each of every one of you has failed.",
            "Are you all trying for a Section 8?",
            "Which of you numbnuts let us down?",
            "You have dishonored this entire unit.",
            "You are the sorriest excuses for soldiers I have ever seen!",
            "Pain is weakness leaving the body!",
            "Down and give me twenty!",
            "Get with the program!",
            "If I have to crack some skulls, I will!",
            "That was an amazing killing spree... by the other team!",
            "You are all dishonorably discharged.",
            "Screamin' eagles!",
            "The last word out of your sorry mouth will be 'Sir!, and it will be loud!",
            "You are scum! You are nothing but a bunch of cowards!",
            "You are a spineless worm! You are a mistake of nature! You are walking vomit!",
            "You are a maggot hatched from a mutant maggot egg!",
            "You sissified maggot scum have just signed your death warrants!",
            "I am going to claw my way down your throat and tear out your very soul!",
            "Take your lumps like a man, Private Twinkletoes.",
            "Each and every one of you will be sent off to your mama in a box!",
            "I join this team just to kill maggots like you!",
            "You are all weak! You are all bleeders!",
            "Last one alive, lock the door!",
            "You deserve a medal, doc.",
            "I have rescued my Intelligence.",
            "I... am... on... Fi-are!",
            "We have you surrounded, at least from this side!",
            "I'm-a execute each and every last one of you!",
            "I'll be sure to inform your next of kin.",
            "Help me commandeer my point!",
            "Man... on... the... point, numb nuts.",
            "C'mere, cupcake.",
            "If God had wanted you to live, he would not have created me!",
            "This is not a camping trip, Sheila. This is war- AND I LOVE IT!",
            "You just got dominated, Bilbo Baggins! (Also: Basbo Bibbins, Barbel Bapkins, Bablo Brabbins, Balbo Biggins)",
            "Your country did not prepare you for the level of violence you will meet on my battlefield!",
            "Aww, am I too violent for you, cupcake?",
            "The next time you want to kill a man, look him in the eyes!",
            "You are a coward, and you've DIED like one!",
            "I will send my condolences to your kangaroo wife.",
            "Now hear this, camper: you are not WANTED on my beloved battlefield!",
            "You will NOT turn my battlefield into a camp ground!",
        ],
    'red_sniper' : [
            "G'day!",
            "Crikey!",
            "Boom. headshot.",
            "Let's see how much blood's in ya!",
            "You best keep lyin' down...",
            "No Worries!",
            "Bloody beaut!",
            "That funeral ain't gonna be open casket.",
            "That's some shonky business right there!",
            "Thanks fer standin' still, wanker!",
            "Standin' around like a bloody idiot!",
            "This is going to go be a real piece of piss, you bloody fruit shop owners.",
            "Everything above your neck's going to be a fine red mist.",
            "Wave goodbye to ya head, wanker!",
            "Bombs away!",
            "Jarate!",
            "God save the Queen!",
            "Spies, bloody USELESS!",
            "You got blood on my knife, mate.",
            "Psssst! He he.",
            "Should've save a bullet for some of you, blokes!",
            "You'll be needin' another use for that neck!",
            "I've slept in the corpse of water buffalo tougher than you!",
            "All your heads look bloody twelve feet tall!",
            "You better hold onto your head, mate!",
            "I'm gonna turn you into colored rain!",
            "That helmet's gonna make a nice bowl for your brains!",
            "Keep yubbin' that big mouth, while it's still attached to your bloody neck.",
            "The bullets come out of the slim end, mate!",
            "All rockets, no brains, eh mate?",
            "At ease! Hahaha!",
            "I owned ya, ya pickle-headed drongo!",
            "Take that, ya rocket-hoppin' simpleton!",
            "Ah, lend us ya shovel, so I can dig ya grave!",
            "Dominated, ya ploddin' potata-head!",
            "I just bagged the worlds fattest man!",
            "There was you, very full of yourself. Then, very briefly surprised. Then, dead.",
            "Oh my god, you've been shot. Did you get a look at the handsome rogue who did it?",
            "Here's a touching story. Once upon a time you died and I lived happily ever after. The end.",
        ],
    'red_scout' : [
            "Bonk!",
            "Boink!",
            "Pancakes.",
            "Play ball! (or Weeaboo!)",
            "Eat my dust!",
            "Let's waste 'em!",
            "Let's get 'em!",
            "Woo hoo!",
            "Say goodbye to ya kneecaps, chucklehead!",
            "Here's a schematic for ya: MY ASS!",
            "This is a real frickin' embarrassment!",
            "Aw, jeeze!",
            "This sucks!",
            "I... hate... doctors!",
            "What the hell is your guys' problem?",
            "Come on, doc, do it!",
            "What the hell was that crap?",
            "Hit the bricks, pal, you're done.",
            "Docta, docta, docta...",
            "This sucks on ice.",
            "Yo, batter up!",
            "Hey knucklehead, I'm talkin' to you!",
            "I oughta' be on a baseball card!",
            "You knuckleheads ain't even worth the effort!",
            "Hey, is somebody keepin' track of my heads batted in?",
            "How's the weather over there, dumbass? Get to the freakin' point!",
            "Wave goodbye to your secret crap, dumbass!",
            "I got it, I got it, I got it!",
            "No problem!",
            "I'm not even winded.",
            "Yeah, it's ours now!",
            "I broke your stupid crap, moron!",
            "Eat it, fatty!",
            "I. Eat. Your. Sandwiches, I eat 'em up!",
            "I- Is anyone even payin' attention to me?",
            "Get on the freakin' point, dumbass!",
            "Oooh yeah, you're real scary.",
            "How's that feel, wimp?",
            "I'm runnin' circles around ya!",
            "You got anything smart to say now?",
            "Not so tough now, are ya? Are ya?!",
            "I'm gonna headbutt'cha, I'm gonna headbutt'cha, I'm gonna headbutt'cha!",
            "Yeah, come get some, ya frickin' wuss.",
            "I'm battin' a thousand.",
            "Stand on the freakin' point, you moron!",
            "Yeah, why don't you come over and say that to my face, tough guy?",
            "Freakin' unbelievable.",
            "Ya head's a freakin' bat magnet!",
            "Way to go, pally!",
            "Hey, a lotta good that gun didja!",
            "Nice hussle tons-of-bun. Next time eat a salad!",
            "I'm not even winded.",
            "Yeah, thanks, doc.",
            "If ya order now, I'll throw in a second beatin' absolutely free!",
            "Here's something you shoulda built: a not dyin' machine.",
            "A lot a good that hard hat didja!",
            "Yeah, I dare ya! Ragequit! Make us both happy!",
            "Don't you ever cross me again!",
            "Depth perception, pal!",
            "I love my ball!",
            "Oh sorry, I didn't mean to hit ya. Oh wait, yeah I did!",
            "Bada-schwing!",
            "Hey, I found my ball!",
            "Alright, I feel good!",
            "I'm a freakin' blur here!",
            "Wananananana.",
            "It ain't your day Pancakes!",
            "No seriously, you all suck.",
            "Suck it, Bra!",
            "I don't know who to thank first. Oh I know, ME!",
        ],
    'red_pyro' : [
            "OUUUMMMPHHHH MMMPPFFHHH MPFHH!",
        ],
    'red_medic' : [
            "Did the Frauleins have their Mittelschmerz?",
            "All I can tell you about this next procedure is that it will be... excruciating!",
            "Eins, zwei, drei... Ugh, I do not think we brought enough body bags.",
            "Hello Frauleins!",
            "The healing is not as rewarding as the hurting!",
            "The healing leaves little time for the hurting!",
            "Oops! That was not medicine!",
            "I healed the man who will kill you.",
            "Would you like a second opinion? You are also ugly!",
            "Aus! Aus!",
            "Can you feel the Schadenfreude?",
            "Zat wasn't very good Sanitation.",
            "Did zat sting? Sorry!",
            "That was Doctor Assisted Homicide!",
            "I am the Ubermensch!",
            "Standing near the point does nothing. Get on the point Dummkopfs!",
            "Idiot! Get on ze point!",
            "Danke, Dummkopfs!",
            "Fire! Fire!",
            "I'm melting!",
            "Everyone! I am on fire!",
            "I am fully charged!",
            "Gesundheit!",
            "Oktoberfest!",
            "Hold still, Schweinhunds. This will only sting for a moment.",
            "You are trying my patience!",
            "Haha, what a bloodbath!",
            "Auf Wiedersehen, Dummkopfs!",
            "Get on the point Dummkopfs!",
            "Turn your head and cough.",
            "I'm going to saw through your bones!",
            "Prepare for your examination.",
            "Thank you Herr Doctor!",
            "Thank you my hard-hatted friend!",
        ],
    'red_heavy' : [
            "Who touch my gun?!",
            "Entire team is babies!",
            "Cry some more!",
            "Keep crying, baby!",
            "I'm coming for you!",
            "I was told we would be fighting men!",
            "All of you are dead!",
            "You! Yes, you! You are dead!",
            "Which one of you is crying?",
            "Dah svidaniya!",
            "I love this doctor!",
            "You're great, doctor!",
            "What sick man sends babies to fight me?",
            "Let us fight man versus tiny baby man!",
            "Go, go, davai!",
            "I hear someone building diaper changing station!",
            "It was long trip.",
            "I killed many cowards to get this!",
            "Eh, not usually my job, but...",
            "We must push little cart!",
            "Forward, glorious cart!",
            "No! Cart has stopped moving!",
            "Cart is moving the wrong way!",
            "Bomb cart will not push self.",
            "I AM BULLETPROOF!",
            "Get behind me, doctor!",
            "HIDE, COWARDS!",
            "Now, it's good time to run cowards!",
            "Now, it's my killing time!",
            "I spy with my little eye!",
            "Don't run! It's just ham!",
            "What was that, Sandvich? 'Kill them all'? Good idea! Hahahaha!",
            "Bologna! Perfect fuel for killing tiny cowards!",
            "Sandvich and me going to beat your ass!",
            "You're a loose cannon, sandvich! But you are a damn good cop!",
            "Ah, so filling! Hahahahaha!",
            "That was delicious!",
            "Moist and delicious!",
            "om nom nom, om nom.",
            "Engineer is credit to team!",
            "You are so small! It's funny to me!",
        ],
     'red_demoman' : [
            "Oh, they're gonna have to glue you back together ... in Hell!",
            "G-gonna blow your ass on the grass and I'm the grass...man...punk...",
            "They're gonna hafta' bury whats left of ye in a soup can!",
            "-and that's what you get for touching that.",
            "Oh, they're gonna find ya all dead in the alley with cats licking at ya!",
            "Next time you'll bloody ask before you stand on my point.",
            "Stand on the bloody point, ya half-wit!",
            "Now it's our flippin' point!",
            "Iluvevery, single... one of ye... not you.",
            "Imagine if I hadn't been drunk.",
            "If I wasn't the man I was, I'd kiss ya.",
            "I'm drunk - you don't have an excuse!",
            "I feel like every bone in me body's broke!",
            "Ooooh, I've realllly hit rock bottom!",
            "I did what I could!",
            "Thankfully, I already don't remember this.",
            "Bloody hell!",
            "Buck up, lads! We'll got them next time.",
            "I almost joined their bloody team!",
            "We are sorry, bunch of losers!",
            "How's that feel, ya blockhead?",
            "KA-BOOOOOOOM!",
            "KA-BLOOEEEEEEEY!",
            "Don't fret boyo, I'll be gentle!",
            "Oh, I'm gonna beat you so hard, you'll have a twitch.",
            "All ya dandies, prancin' about with your heads full of eyeballs!",
            "I'm gonna blast ya into thin glue.",
            "Not one of ya's gonna survive this!",
            "In your language: Eat lead, laddies!",
            "You appear to 'ave trodden on a mine!",
            "Oh, I'm goin' to liquefy ya...",
            "I've been Shagging ya Wife!",
        ],
    'red_engineer' : [
            "You ladies shoulda' oughta' brought some menfolk with ya.",
            "I built that.",
            "Cream gravy!",
            "Another satisfied customer!",
            "I told ya don't touch that darn thing.",
            "Start prayin', boy!",
            "Take it like a man, son/shorty.",
            "I'm gonna beat you like a rented mule, boy.",
            "Spy sappin' my sentry!",
            "Erectin' a dispenser!",
            "Teleporter goin' up!",
            "Sentry down!",
            "Teleporter down!",
            "Goddamn spies destroy everything I create!",
            "Hoo wee, would ya look at that?",
            "Hoo wee, makin' bacon!",
            "C'mere, sissy!",
            "Son, I'm gonna blow that dumb look right off your stupid face.",
            "Dag-nabbit damn it!",
            "Good night Irene!",
            "(when defending a control point) Plant yourself on the point, mister!",
            "Now I've seen everything...",
            "I'm moving this.",
            "Heavy load comin' through!",
            "Some times you just need a little less gun.",
            "Ain't that a cute lil' gun?",
            "This thing ain't on auto-pilot, son!",
            "Erectin' a statue of a moron!",
            "That there's a gold plated kill!",
            "Least you ain't worthless any more.",
        ],
    }